# Generated by Django 3.0.2 on 2020-01-02 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191226_0146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
