# Generated by Django 3.1.4 on 2021-01-05 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='File',
        ),
    ]
