# Generated by Django 3.1.4 on 2021-01-05 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210105_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='author',
            new_name='uploadby',
        ),
    ]
