# Generated by Django 3.1.4 on 2021-01-05 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210105_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='uploadby',
            new_name='Uploaded by',
        ),
    ]
