# Generated by Django 3.1.4 on 2021-01-05 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210105_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='Uploaded by',
            new_name='owner',
        ),
    ]
